### PR TITLE
Added a simple sketch of a wiki

### PR DESCRIPTION
**Pull request by magdesign**
Let me know what you think and which are the most important informations you'd like me to put in.
I guess already screenshots are great to gain new users.
There is a detailed compile instruction for pinephonepro users.

See preview here: https://github.com/magdesign/osmin/wiki

### CODE REVIEW

**Comment by janbar** [comment]
Great work. We will add pages to manage GPX files, imported or generated by tracker, and to manage favorites too.
I try to make this app simple to use as possible and also robust. My personal usage is to ride by cycle or motorbike without any internet connection, so completely offline.

**Comment by magdesign** [comment]
Great, I was looking for such an app since a long time. Going to travel the world by bicycle and in need of a simple offline navigator running on Linux phones, osmin is amazing!

Added some info about the tracker in the wiki, will also update with compile information for other Linux distros...

**Comment by janbar** [comment]
I have to find how I can merge the wiki pages in the project ... else about android I wrote few lines in the readme file. I could update this part (android) later.

**Comment by janbar** [comment]
Yep,found that: git clone YOUR_FORKED_REPO.wiki.git

**Comment by magdesign** [comment]
Cant you directly merge it when logging in to Github on the browser?

**Pull request merged**
